//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module6_3.Modul
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessUser
    {
        public int intAccessID { get; set; }
        public Nullable<int> intUserId { get; set; }
        public Nullable<System.DateTime> dCreated { get; set; }
        public Nullable<int> intTabID { get; set; }
        public Nullable<int> intGroupAccessId { get; set; }
        public Nullable<int> intLocationId { get; set; }
    
        public virtual AccessTab AccessTab { get; set; }
    }
}
