//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module6_3.Modul
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccessTab()
        {
            this.AccessUsers = new HashSet<AccessUser>();
        }
    
        public int intTabID { get; set; }
        public string strTabName { get; set; }
        public string strDescription { get; set; }
        public string strTabUrl { get; set; }
        public string strTabGroupName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessUser> AccessUsers { get; set; }
    }
}
